[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NPF"
authors = [{name = "Tom Barbette", email = "t.barbette@gmail.com"}]
dynamic = ["version", "description"]
