name: Sphinx CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: tbarbette/sphinx-action@master
      with:
        docs-folder: "docs/"
